import Head from 'next/head'

import {motion as m} from 'framer-motion'

export default function Home() {
  return (
    <m.div initial={{y:"100%"}} animate={{y:"0%"}} transition={{duration: 0.75, ease:"easeOut"}} exit={{opacity:1}}
    className="text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-100 lg:px-48 px-16"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <main>
    <div className='mt-80 mb-28 p-1 overflow-hidden'>
      <m.h1 animate={{y:"0%"}} initial={{y: "100%"}} transition={{delay: 0.5, duration:0.5}}
      className='text-6xl text-center lg:text-right lg:text-9xl'>Welcome!</m.h1>
    </div>

    <div className='flex justify-between'>
           <div className=''>
            <h2>Design</h2>
            <h2>Company</h2>
            <h2>2022</h2>
           </div>
           <div className=''>
            <h3>Makes you smile.</h3>
            <h3>Makes you smile.</h3>
            <h3>Makes you smile.</h3>
           </div>
    </div>
   
   </main>
      

      
    </m.div>
  )
}
